// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmqisvutyndlzpqcwyym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtcWlzdnV0eW5kbHpwcWN3eXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwMjYxMDcsImV4cCI6MjEwNDYwMjEwN30.hgT1qKTU3ONHfsNvYu_KOAY1nRq4dWhtt9kGLRV8-44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
