// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mguavdrifefyzswdiqww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndWF2ZHJpZmVmeXpzd2RpcXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NzIwNzIsImV4cCI6MjA4ODU0ODA3Mn0.vm6AGKdlSZDYa-0QKSiUh7lWqkC9Y9b9Pf_f-RmAKxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});